services:
  app:
    build: .
    container_name: plazofijo_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=plazo_fijo_db
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
    command: >
      sh -c "cp -n .env.example .env &&
             composer install --no-interaction &&
             php artisan key:generate &&
             until php artisan db:show > /dev/null 2>&1; do echo 'Esperando DB...'; sleep 2; done &&
             php artisan migrate --seed --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: postgres:15-alpine
    container_name: plazofijo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: plazo_fijo_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
